tenets:
  - name: find-funcs
    flows:
      codelingo/review:
        comment: |
          Error strings should not be capitalized (unless beginning with proper nouns 
          or acronyms) or end with punctuation, since they are usually printed following
          other context.
      codelingo/rewrite:
    query: |
      import codelingo/ast/go
      
      go.call_expr(depth = any):
        # filename as fName
        # regex(/_test.go$/", fName)
        go.selector_expr:
          go.ident:
            name == "assert"
          go.ident:
            name == "Equal"
        go.args:
          @review comment
          go.basic_lit:
            sibling_order == 1
            kind == "string"
          go.call_expr:
            sibling_order == 2
            go.selector_expr:
              go.ident:
                name == "err"
              go.ident:
                name == "Error"